version: "3.7"
services:
  app:
    build:
      args:
        user: root
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: home_theater
    container_name: home_theater
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - home_theater_network
  db:
      image: mysql:8.0
      container_name: home_theater_mysql
      restart: unless-stopped
      environment:
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # Specify the root password here
          MYSQL_PASSWORD: ${DB_PASSWORD}
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
      volumes:
          - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      networks:
          - home_theater_network
  nginx:
    image: nginx:alpine
    container_name: home_theater_nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - home_theater_network
networks:
  home_theater_network:
    driver: bridge
